### ISSUE TITLE
NullPointerException in VideoIntentReceiver (CCL 2.0)

### ISSUE THREAD

**Issue by apkelly** [googlecast/CastCompanionLibrary-android#176] opened 2015-05-07 06:05 UTC
I'm seeing lots of the following stack traces in my Crashlytics console.

java.lang.RuntimeException: Unable to start receiver com.google.android.libraries.cast.companionlibrary.remotecontrol.VideoIntentReceiver: java.lang.NullPointerException
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2237)
       at android.app.ActivityThread.access$1500(ActivityThread.java:131)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4754)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at com.google.android.libraries.cast.companionlibrary.remotecontrol.VideoIntentReceiver.onReceive(VideoIntentReceiver.java:64)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2230)
       at android.app.ActivityThread.access$1500(ActivityThread.java:131)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:4754)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at dalvik.system.NativeStart.main(NativeStart.java)

It was also present in the older version of the CCL

java.lang.RuntimeException: Unable to start receiver com.google.sample.castcompanionlibrary.remotecontrol.VideoIntentReceiver: java.lang.NullPointerException
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2502)
       at android.app.ActivityThread.access$1700(ActivityThread.java:149)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
       at android.os.Handler.dispatchMessage(Handler.java:122)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5122)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: java.lang.NullPointerException
       at com.google.sample.castcompanionlibrary.remotecontrol.VideoIntentReceiver.onReceive(VideoIntentReceiver.java:82)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:2487)
       at android.app.ActivityThread.access$1700(ActivityThread.java:149)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1286)
       at android.os.Handler.dispatchMessage(Handler.java:122)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5122)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by naddaf** [comment] 2015-05-13 07:11
I need reproduction steps since I am not seeing such issue on my side.

**Comment by apkelly** [comment] 2015-05-13 11:32
It seems to be the same line of code in the two different versions of the library.

KeyEvent keyEvent = (KeyEvent) intent.getExtras().get(Intent.EXTRA_KEY_EVENT);

since intent.getAction() is called successfully at the top of the containing method, I can only assume this call is failing because there are no extras available. Could this be caused by a killed app being brought back to the foreground?

**Comment by naddaf** [comment] 2015-05-15 19:08
This should be fixed in v2.0.1

**Closed by naddaf** 2015-05-15 19:08 UTC
