### ISSUE TITLE
 java.lang.OutOfMemoryError  at FetchBitmapTask.java:80

### ISSUE THREAD

**Issue by mntgoat** [googlecast/CastCompanionLibrary-android#150] opened 2015-01-26 20:06 UTC
I don't remember if this version of my app was released with version 1.12 or 1.13 of the CastCompanionLibrary but anyways I've seen this exception a few times. It isn't happening a lot but I figured I should report it. 

java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.OutOfMemoryError
at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:709)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:685)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:723)
at com.google.sample.castcompanionlibrary.utils.FetchBitmapTask.doInBackground(FetchBitmapTask.java:80)
at com.google.sample.castcompanionlibrary.utils.FetchBitmapTask.doInBackground(FetchBitmapTask.java:38)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 3 more

**Comment by naddaf** [comment] 2015-01-26 20:32
What is the device's memory and what is the size of image?

**Comment by mntgoat** [comment] 2015-01-26 20:45
I don't see a way to tell the device memory on the play dev console or crashlytics. As far as the image, I have no idea of the sizes as they are provided by different third parties. 

If you have a private way for me to share a link, I can send you the crashlytics crash report. 

--Carlos

**Comment by philipgiuliani** [comment] 2016-01-11 15:27
I have the same problem on a debug device which i have here (very very low memory). What about loading the image with some well tested libraries like Glide or Picasso? They do a very well job.

**Comment by naddaf** [comment] 2016-01-11 19:12
Philip, what is the screen size and resolution for your debug device?

**Comment by naddaf** [comment] 2016-01-12 01:11
mntgoat and/or Philip: if I give you a build of CCL, do you have any means to verify if that fixes this issue?

**Comment by mntgoat** [comment] 2016-01-12 02:51
@naddaf sorry but I don't use that part of the code anymore. I do have my own that uses Glide (used to use Picasso) and that didn't really help the problem. My images can be pretty large. Glide has helped because they use a config that uses less memory.

**Comment by philipgiuliani** [comment] 2016-01-12 08:12
@naddaf Hi! I have the following device: http://www.gsmarena.com/samsung_galaxy_tab_10_1_p7510-3894.php

It crashes every time i click on the "currently casting" button (when it opens the VideoCastControllerActivity). I guess because of the large background. Replacing it with Picasso did work for me.

@mntgoat 
The difference of Glide & Picasso is the bitmap format that they use. You can also assign it to picasso, than it will be similar :)

![ram1_1](https://cloud.githubusercontent.com/assets/5446019/12258126/8340fabc-b90c-11e5-889a-e70ff3a8d31b.png)
Source: http://inthecheesefactory.com/blog/get-to-know-glide-recommended-by-google/en

**Comment by naddaf** [comment] 2016-01-12 14:28
Philip, the mentioned device seems to have 1G of RAM so it is strange that
it would crash on OOM but nonetheless, I can give you an updated CCL to see
if that addresses the issue you are seeing. If I do that, can you test it
on that device?

Thanks
Ali.

P.S. Is this reproducible in CastVideos app for you?

**Comment by naddaf** [comment] 2016-01-21 19:43
v2.7.2 has done some work to address this, I am closing this due to the lack of further interest.

**Closed by naddaf** 2016-01-21 19:43 UTC

**Comment by daedamr** [comment] 2016-05-26 13:14
This is still reproducible for us, for library version 2.8.3, and strange enough for devices that are no low memory (nexus 5x, samsung s6 etc):

```
Caused by java.lang.OutOfMemoryError
android.graphics.BitmapFactory.nativeDecodeStream (BitmapFactory.java)
android.graphics.BitmapFactory.decodeStreamInternal (BitmapFactory.java:709)
android.graphics.BitmapFactory.decodeStream (BitmapFactory.java:685)
com.newrelic.agent.android.instrumentation.BitmapFactoryInstrumentation.decodeStream (BitmapFactoryInstrumentation.java:91)
com.google.android.libraries.cast.companionlibrary.utils.FetchBitmapTask.doInBackground (FetchBitmapTask.java:117)
com.google.android.libraries.cast.companionlibrary.utils.FetchBitmapTask.doInBackground (FetchBitmapTask.java:39)
android.os.AsyncTask$2.call (AsyncTask.java:288)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:841)
```

I could not reproduce this, it is just reported by Fabric, and in logs I see from the screens visited as this happened in VideoCastControllerFragment.

**Comment by naddaf** [comment] 2016-05-26 13:35
Please take a look at the code; I am resampling before downloading so that is all that I can do and that shouldn't cause any OOM on a device such as 5X.

**Comment by daedamr** [comment] 2016-05-26 14:52
Yes, I checked the code from FetchBitmapTask and i saw the sampling. And it is strange that this is reported on devices that should not have problems with memory. 

I am testing on a nexus 5X right now and what i am seeing with memory monitoring is that memory is deallocated ok when entering and exiting the VideoCastControllerFragment, but it is steadily increasing (without deallocation) when closing and reopening the device screen. Then checked what happens in onResume it is called each time updateMetadata() that updates the image. Not sure if it helps.

Also the bitmap in UrlAndBitmap may be better to have a soft reference: https://developer.android.com/training/displaying-bitmaps/manage-memory.html#inBitmap
