### ISSUE TITLE
Confirmation of issue #171

### ISSUE THREAD

**Issue by mntgoat** [googlecast/CastCompanionLibrary-android#174] opened 2015-04-22 15:30 UTC
I can confirm issue #171 is happening. I added a comment there but I think it will get ignored because it is closed already so I am opening this new issue. 

I tried the keycut app with a pressy and the issue happened. I also tried 3 apps which I believe use the CCL and they all had the issue. The reported of #171 tried the Cast Videos app as well. 

I also tried it with the Samsung music player and normal headphones. I played music with the headphones, paused it, cast something, and then stopped casting, even killed the app, and I could not use the headphone controls anymore. I had to start playback again by hand for the music player to get headphone commands again. 

I then tried the Samsung music player but this time I cast using YouTube, and as soon as I stopped casting the Samsung music player would start receiving headphone commands again.

**Comment by naddaf** [comment] 2015-05-13 16:44
Since I can't reproduce this myself, I need your help in testing a potential fix, please contact me via email (ali.naddaf@gmail.com) so I can work with you on that.

**Comment by naddaf** [comment] 2015-05-15 19:06
Fixed in v2.0.2

**Closed by naddaf** 2015-05-15 19:06 UTC
