### ISSUE TITLE
Crash when disconnecting wifi

### ISSUE THREAD

**Issue by path2727** [googlecast/CastCompanionLibrary-android#170] opened 2015-04-13 18:48 UTC
Steps

1) connect to chromecast receiver
2) play a video (plays on receiver)
3a) put android device in airplane mode  or disable wifi
4) attempt to play another video ( i think the crash happens on #3 though, i am just trying to play another video by chance)

It doesn't reproduce 100% of the time.

I want to add code to catch this exception.

java.lang.IllegalStateException: Not connected. Call connect() and wait for onConnected() to be called.
at com.google.android.gms.common.internal.zzk.zzfc(Unknown Source)
at com.google.android.gms.common.internal.zzk.zzjb(Unknown Source)
at com.google.android.gms.internal.zzju.disconnect(Unknown Source)
at com.google.android.gms.common.api.zzd.zzao(Unknown Source)
at com.google.android.gms.common.api.zzd.disconnect(Unknown Source)
at com.google.android.libraries.cast.companionlibrary.cast.BaseCastManager.disconnectDevice(BaseCastManager.java:262)
at com.google.android.libraries.cast.companionlibrary.cast.BaseCastManager.onDeviceSelected(BaseCastManager.java:204)
at com.google.android.libraries.cast.companionlibrary.cast.CastMediaRouterCallback.onRouteUnselected(CastMediaRouterCallback.java:64)
at android.support.v7.media.MediaRouter$GlobalMediaRouter$CallbackHandler.invokeCallback(MediaRouter.java:2480)
at android.support.v7.media.MediaRouter$GlobalMediaRouter$CallbackHandler.handleMessage(MediaRouter.java:2427)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5221)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by aaearon** [comment] 2015-04-16 15:08
I also have reports of users experiencing this same issue.

**Comment by Redwid** [comment] 2015-04-20 13:22
The same stack trace if user switched off TV when cromecast connected to TV USB:
FATAL EXCEPTION: main
    java.lang.IllegalStateException: Not connected. Call connect() and wait for onConnected() to be called.
            at com.google.android.gms.common.internal.zzk.zzfc(Unknown Source)
            at com.google.android.gms.common.internal.zzk.zzjb(Unknown Source)
            at com.google.android.gms.internal.zzju.disconnect(Unknown Source)
            at com.google.android.gms.common.api.zzd.zzao(Unknown Source)
            at com.google.android.gms.common.api.zzd.zza(Unknown Source)
            at com.google.android.gms.common.api.zzd$7.zzap(Unknown Source)
            at com.google.android.gms.common.api.zzd$7.zzia(Unknown Source)
            at com.google.android.gms.common.internal.zzk$zzg.zzje(Unknown Source)
            at com.google.android.gms.common.internal.zzk$zza.zzc(Unknown Source)
            at com.google.android.gms.common.internal.zzk$zza.zzi(Unknown Source)
            at com.google.android.gms.common.internal.zzk$zzc.zzjg(Unknown Source)
            at com.google.android.gms.common.internal.zzk$zzb.handleMessage(Unknown Source)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by path2727** [comment] 2015-04-22 00:39
i imported the ccl as a library in my project

here is where it was crashing

https://github.com/googlecast/CastCompanionLibrary-android/blob/master/src/com/google/android/libraries/cast/companionlibrary/cast/BaseCastManager.java#L262

 wrapped the disconnect call with an isConnected check (only disconnect if connected).

then just to be sure, i caught an exception

here is my fix

            if( mApiClient.isConnected()) {
                try {
                    mApiClient.disconnect();
                } catch( Exception e ) {
                    LOGE(TAG, "error", e);
                }
            }

**Comment by dodgex** [comment] 2015-04-22 11:23
yeah same issue for me. isConnected check fixed it for me

**Comment by fanno** [comment] 2015-04-22 14:47
I have had this error also 5 times total.

I will also try the mApiClient.isConnected() check.

-Thanks

**Comment by tmack8001** [comment] 2015-04-22 15:13
It would be nice if someone from the community packaged this up into a PR that Google would allow to be merged as a patch bugfix

**Comment by dodgex** [comment] 2015-04-22 15:30
@tmack8001 done. lets hope they'll merge it. ;)

**Comment by mpatt3970** [comment] 2015-05-01 19:00
I'm seeing the same crash when connecting to a Nearby Device. Steps to repro : 
1) Turn off wifi
2) Let app search for a cast device.
3) Connect to Nearby device

It seems that after the route is selected, it is disconnected before the connection completes.

**Comment by naddaf** [comment] 2015-05-13 07:09
This is caused by a bug in Play Services. That bug will be fixed in a future update to Play Services and meanwhile, I have aded a conditional to improve it; a better conditional should have included "isConnecting()" check as well but that will cause a NPE due to the very same bug in the play services.

**Closed by naddaf** 2015-05-13 07:09 UTC
