### ISSUE TITLE
reopen ticket /issue? and or just question about it

### ISSUE THREAD

**Issue by fanno** [googlecast/CastCompanionLibrary-android#161] opened 2015-03-29 18:39 UTC
Hello

I have same error as in #23 i believe. 

should i create new issue ? or use the same one ?

**Comment by naddaf** [comment] 2015-03-29 18:40
And what version of the CCL are you using?

**Comment by fanno** [comment] 2015-03-29 18:43
The error is with version before 2.0.0 (believe it was 1.14)

I have just updated to 2.0.0, so i can't really "revert" at this point in time. but my main "question" is more or less if there is anything i can or should do .

-Thanks

**Comment by naddaf** [comment] 2015-03-29 18:45
As far as I understand, the exception is caught and is not causing any problem, or is it?

**Comment by fanno** [comment] 2015-03-29 18:47
I don't know =( it was reported to me on https://play.google.com/apps/publish/ .... i can't recreate it my self so also hard to know if there is a problem. but normaly uncaught crash are a problem.!

**Comment by fanno** [comment] 2015-03-29 18:47
I don't know =( it was reported to me on https://play.google.com/apps/publish/ .... i can't recreate it my self so also hard to know if there is a problem. but normaly uncaught crash are a problem.!

**Comment by naddaf** [comment] 2015-03-29 19:16
I have to dif deeper into the Play Services; I can wrap that piece in a try-catch but it doesn't seem write to me. Do you know what version of Play Services is running on the device that is throwing that exception?

**Comment by naddaf** [comment] 2015-03-29 19:17
And is this an isolated instance or there is a lot of that crash reported?

**Comment by fanno** [comment] 2015-03-29 19:23
only have one report yes. don't have a whole lot of users only 2380 / 2310 or so right now

Let me know if there is anything i can do. i dont mind geting my hands dirty if it is something i can do =P

**Comment by fanno** [comment] 2015-03-29 19:33
report was on
android 5.0
xperia z3 compact (d5803)

in case that is usefull

**Comment by naddaf** [comment] 2015-03-29 22:02
As long as it is one single instance, I wouldn't worry about it (I haven't
seen such issue before). If it keeps on happening, then we can look further.

**Comment by naddaf** [comment] 2015-03-30 15:30
I'll close the issue for now since it seems like an isolated incident and am not able to reproduce. If you see more of these reports, please let me know.

**Closed by naddaf** 2015-03-30 15:30 UTC
