### ISSUE TITLE
Error inflating class ...MiniController. Resources$NotFoundException

### ISSUE THREAD

**Issue by philipgiuliani** [googlecast/CastCompanionLibrary-android#275] opened 2016-02-22 08:11 UTC
I updated my library today by removing the old one and adding the dependency from jCenter to my build.gradle.

In all activities with an MiniController i'm getting the following error now:
```
android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class com.google.android.libraries.cast.companionlibrary.widgets.MiniController
```

Did i miss something that i have to change after upgrading?

**Comment by naddaf** [comment] 2016-02-22 08:12
What version were you using before?

**Comment by philipgiuliani** [comment] 2016-02-22 08:14
I upgraded from 2.7.1

**Comment by naddaf** [comment] 2016-02-22 08:18
I can't think of anything in particular and certainly is not what others are experiencing. Clean your project completely and see if that helps or not.

**Comment by philipgiuliani** [comment] 2016-02-22 09:41
Thanks for your fast answers. I attached the whole stacktrace. On the bottom i found the problem:

Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_mini_controller_upcoming_play.xml from drawable resource ID #0x7f0200f4
                                                                   	at android.content.res.

I can remember this file was not found in 2.7.1 already, and i just removed the button inside my project beacuse i didn't need it. Why nobody else has this problem?

```
02-22 10:37:26.207 12795-12795/com.youtv.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.youtv.android, PID: 12795
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.youtv.android/com.youtv.android.ui.MainActivity}: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class com.google.android.libraries.cast.companionlibrary.widgets.MiniController
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                    Caused by: android.view.InflateException: Binary XML file line #23: Binary XML file line #23: Error inflating class com.google.android.libraries.cast.companionlibrary.widgets.MiniController
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256)
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
                                                                       at com.youtv.android.ui.MainActivity.onCreate(MainActivity.java:57)
                                                                       at android.app.Activity.performCreate(Activity.java:6237)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                    Caused by: android.view.InflateException: Binary XML file line #23: Error inflating class com.google.android.libraries.cast.companionlibrary.widgets.MiniController
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                       at com.youtv.android.ui.MainActivity.onCreate(MainActivity.java:57) 
                                                                       at android.app.Activity.performCreate(Activity.java:6237) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                       at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:619)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                       at com.youtv.android.ui.MainActivity.onCreate(MainActivity.java:57) 
                                                                       at android.app.Activity.performCreate(Activity.java:6237) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                    Caused by: android.view.InflateException: Binary XML file line #125: Binary XML file line #125: Error inflating class ImageButton
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
                                                                       at com.google.android.libraries.cast.companionlibrary.widgets.MiniController.<init>(MiniController.java:103)
                                                                       at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                       at com.youtv.android.ui.MainActivity.onCreate(MainActivity.java:57) 
                                                                       at android.app.Activity.performCreate(Activity.java:6237) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                    Caused by: android.view.InflateException: Binary XML file line #125: Error inflating class ImageButton
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:782)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:838)
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                       at com.google.android.libraries.cast.companionlibrary.widgets.MiniController.<init>(MiniController.java:103) 
                                                                       at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:838) 
                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:256) 
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109) 
                                                                       at com.youtv.android.ui.MainActivity.onCreate(MainActivity.java:57) 
                                                                       at android.app.Activity.performCreate(Activity.java:6237) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                    Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_mini_controller_upcoming_play.xml from drawable resource ID #0x7f0200f4
                                                                   	at android.content.res.
```

**Comment by naddaf** [comment] 2016-02-22 14:52
That resource is there in the library, see [this](https://github.com/googlecast/CastCompanionLibrary-android/blob/master/res/drawable/ic_mini_controller_upcoming_play.xml) and [this](https://github.com/googlecast/CastCompanionLibrary-android/blob/master/res/drawable-sw600dp/ic_mini_controller_upcoming_play.xml). You need to see why in your environment it cannot be found. What phone are you using?

**Comment by philipgiuliani** [comment] 2016-02-22 14:53
Good question. I have a Nexus 6P (Simulator + Real device). Never tried another one.

**Comment by philipgiuliani** [comment] 2016-02-22 14:55
![bildschirmfoto 2016-02-22 um 15 55 13](https://cloud.githubusercontent.com/assets/5446019/13221645/bbeaaeea-d97c-11e5-8f29-89239ff24ad9.png)

This change fixes the issue for me.

**Comment by naddaf** [comment] 2016-02-22 14:57
I test on N6p so it is not your device. Since you said it was happening with 2.7.1 as well, it is not the aar packaging in jCenter either; try CastVideos-android (with jCenter) and see if that works for you.

**Comment by philipgiuliani** [comment] 2016-02-22 15:05
Thats right. I forgot about that change completely when i did it last time. I'll try another device now and see if i can find out...

**Comment by naddaf** [comment] 2016-02-22 21:35
You can try using a lower version. I am closing this since I am not able to reproduce and the resource does exist in the package.

**Closed by naddaf** 2016-02-22 21:35 UTC

**Comment by philipgiuliani** [comment] 2016-02-22 22:45
Ok thanks. I will try to downgrade until it works.so i can check the diff! I will keep you up to date.
